use crate::model::{Manifest, Procedure, ProcedureKind};

use super::typescript::rust_type_to_ts;

const GENERATED_HEADER: &str = "\
// This file is auto-generated by vercel-rpc-cli. Do not edit manually.
// Re-run `rpc generate` or use `rpc watch` to regenerate.
";

const QUERY_OPTIONS_INTERFACE: &str = r#"export interface QueryOptions<K extends QueryKey> {
  /**
   * Whether to execute the query. @default true
   *
   * Pass a getter `() => bool` for reactive updates — a plain `boolean` is
   * read once when `createQuery` is called and will not trigger re-fetches.
   */
  enabled?: boolean | (() => boolean);

  /** Auto-refetch interval in milliseconds. Set to 0 or omit to disable. */
  refetchInterval?: number;

  /** Initial data shown before the first fetch completes. */
  placeholderData?: QueryOutput<K>;

  /** Per-call options forwarded to client.query(). */
  callOptions?: CallOptions;

  /** Called when the query succeeds. */
  onSuccess?: (data: QueryOutput<K>) => void;

  /** Called when the query fails. */
  onError?: (error: RpcError) => void;

  /** Called when the query settles (success or failure). */
  onSettled?: () => void;
}"#;

const QUERY_RESULT_INTERFACE: &str = r#"export type QueryStatus = "idle" | "loading" | "success" | "error";

export interface QueryResult<K extends QueryKey> {
  /** The latest successfully resolved data, or placeholderData. */
  readonly data: QueryOutput<K> | undefined;

  /** The error from the most recent failed fetch, cleared on success. */
  readonly error: RpcError | undefined;

  /** Current status of the query state machine. */
  readonly status: QueryStatus;

  /** True while a fetch is in-flight (including the initial fetch). */
  readonly isLoading: boolean;

  /** True after the first successful fetch. Stays true across refetches. */
  readonly isSuccess: boolean;

  /** True when the most recent fetch failed. */
  readonly isError: boolean;

  /** True when placeholderData is being shown and no real fetch has completed yet. */
  readonly isPlaceholderData: boolean;

  /** Manually trigger a refetch. */
  refetch: () => Promise<void>;
}"#;

const MUTATION_OPTIONS_INTERFACE: &str = r#"export interface MutationOptions<K extends MutationKey> {
  /** Per-call options forwarded to client.mutate(). */
  callOptions?: CallOptions;

  /** Called when the mutation succeeds. */
  onSuccess?: (data: MutationOutput<K>) => void;

  /** Called when the mutation fails. */
  onError?: (error: RpcError) => void;

  /** Called when the mutation settles (success or failure). */
  onSettled?: () => void;
}"#;

const MUTATION_RESULT_INTERFACE: &str = r#"export type MutationStatus = "idle" | "loading" | "success" | "error";

export interface MutationResult<K extends MutationKey> {
  /** Execute the mutation. Rejects on error. */
  mutate: (...args: MutationArgs<K>) => Promise<void>;

  /** Execute the mutation and return the result. Rejects on error. */
  mutateAsync: (...args: MutationArgs<K>) => Promise<MutationOutput<K>>;

  /** The latest successfully resolved data. */
  readonly data: MutationOutput<K> | undefined;

  /** The error from the most recent failed mutation, cleared on next attempt. */
  readonly error: RpcError | undefined;

  /** Current status of the mutation state machine. */
  readonly status: MutationStatus;

  /** True while a mutation is in-flight. */
  readonly isLoading: boolean;

  /** True after the most recent mutation succeeded. */
  readonly isSuccess: boolean;

  /** True when the most recent mutation failed. */
  readonly isError: boolean;

  /** Reset state back to idle (clear data, error, status). */
  reset: () => void;
}"#;

const IS_QUERY_OPTIONS_IMPL: &str = r#"const QUERY_OPTIONS_KEYS: string[] = [
  "enabled", "refetchInterval", "placeholderData", "callOptions",
  "onSuccess", "onError", "onSettled",
];

function isQueryOptions(v: unknown): boolean {
  if (v == null || typeof v !== "object") return false;
  return Object.keys(v as object).every(k => QUERY_OPTIONS_KEYS.includes(k));
}"#;

const CREATE_QUERY_IMPL: &str = r#"export function createQuery<K extends QueryKey>(
  client: RpcClient,
  ...args: unknown[]
): QueryResult<K> {
  const key = args[0] as K;

  let inputFn: (() => QueryInput<K>) | undefined;
  let optionsArg: QueryOptions<K> | (() => QueryOptions<K>) | undefined;

  if (typeof args[1] === "function" && args[2] !== undefined) {
    inputFn = args[1] as () => QueryInput<K>;
    optionsArg = args[2] as QueryOptions<K> | (() => QueryOptions<K>) | undefined;
  } else if (typeof args[1] === "function") {
    const probe = (args[1] as () => unknown)();
    if (probe != null && typeof probe === "object" && isQueryOptions(probe)) {
      optionsArg = args[1] as () => QueryOptions<K>;
    } else {
      inputFn = args[1] as () => QueryInput<K>;
    }
  } else if (typeof args[1] === "object") {
    optionsArg = args[1] as QueryOptions<K>;
  }

  function resolveOptions(): QueryOptions<K> | undefined {
    return typeof optionsArg === "function" ? optionsArg() : optionsArg;
  }

  let data = $state<QueryOutput<K> | undefined>(resolveOptions()?.placeholderData);
  let error = $state<RpcError | undefined>();
  let status = $state<QueryStatus>("idle");

  async function fetchData(input?: QueryInput<K>, signal?: AbortSignal) {
    const opts = resolveOptions();
    status = "loading";
    error = undefined;
    try {
      const callArgs: unknown[] = [key];
      if (input !== undefined) callArgs.push(input);
      const mergedCallOptions = signal
        ? { ...opts?.callOptions, signal: opts?.callOptions?.signal
            ? AbortSignal.any([signal, opts.callOptions.signal])
            : signal }
        : opts?.callOptions;
      if (mergedCallOptions) callArgs.push(mergedCallOptions);
      const result = await (client.query as (...a: unknown[]) => Promise<unknown>)(...callArgs) as QueryOutput<K>;
      if (signal?.aborted) return;
      data = result;
      status = "success";
      opts?.onSuccess?.(result);
    } catch (e) {
      if (signal?.aborted) return;
      error = e as RpcError;
      status = "error";
      opts?.onError?.(error);
    } finally {
      if (!signal?.aborted) {
        opts?.onSettled?.();
      }
    }
  }

  $effect(() => {
    const opts = resolveOptions();
    const enabled = typeof opts?.enabled === "function"
      ? opts.enabled()
      : (opts?.enabled ?? true);
    const input = inputFn?.();
    if (!enabled) return;

    const controller = new AbortController();
    void fetchData(input, controller.signal);

    let interval: ReturnType<typeof setInterval> | undefined;
    if (opts?.refetchInterval) {
      interval = setInterval(() => {
        if (!controller.signal.aborted) fetchData(inputFn?.(), controller.signal);
      }, opts.refetchInterval);
    }

    return () => {
      controller.abort();
      if (interval) clearInterval(interval);
    };
  });

  return {
    get data() { return data; },
    get error() { return error; },
    get status() { return status; },
    get isLoading() { return status === "loading"; },
    get isSuccess() { return status === "success"; },
    get isError() { return status === "error"; },
    get isPlaceholderData() { return status !== "success" && data !== undefined; },
    refetch: () => fetchData(inputFn?.()),
  };
}"#;

const CREATE_MUTATION_IMPL: &str = r#"export function createMutation<K extends MutationKey>(
  client: RpcClient,
  key: K,
  options?: MutationOptions<K>,
): MutationResult<K> {
  let data = $state<MutationOutput<K> | undefined>();
  let error = $state<RpcError | undefined>();
  let status = $state<MutationStatus>("idle");

  async function execute(...input: MutationArgs<K>): Promise<MutationOutput<K>> {
    status = "loading";
    error = undefined;
    try {
      const callArgs: unknown[] = [key];
      if (input.length > 0) callArgs.push(input[0]);
      if (options?.callOptions) callArgs.push(options.callOptions);
      const result = await (client.mutate as (...a: unknown[]) => Promise<unknown>)(...callArgs) as MutationOutput<K>;
      data = result;
      status = "success";
      options?.onSuccess?.(result);
      return result;
    } catch (e) {
      error = e as RpcError;
      status = "error";
      options?.onError?.(error);
      throw e;
    } finally {
      options?.onSettled?.();
    }
  }

  return {
    mutate: async (...args: MutationArgs<K>) => { await execute(...args); },
    mutateAsync: (...args: MutationArgs<K>) => execute(...args),
    get data() { return data; },
    get error() { return error; },
    get status() { return status; },
    get isLoading() { return status === "loading"; },
    get isSuccess() { return status === "success"; },
    get isError() { return status === "error"; },
    reset: () => { data = undefined; error = undefined; status = "idle"; },
  } as MutationResult<K>;
}"#;

/// Generates the complete Svelte 5 reactive wrapper file content from a manifest.
///
/// Returns an empty string when the manifest contains no procedures (the caller
/// should skip writing the file in that case).
pub fn generate_svelte_file(
    manifest: &Manifest,
    client_import_path: &str,
    types_import_path: &str,
    _preserve_docs: bool,
) -> String {
    let queries: Vec<_> = manifest
        .procedures
        .iter()
        .filter(|p| p.kind == ProcedureKind::Query)
        .collect();
    let mutations: Vec<_> = manifest
        .procedures
        .iter()
        .filter(|p| p.kind == ProcedureKind::Mutation)
        .collect();

    if queries.is_empty() && mutations.is_empty() {
        return String::new();
    }

    let has_queries = !queries.is_empty();
    let has_mutations = !mutations.is_empty();

    let mut out = String::with_capacity(4096);

    // Header
    out.push_str(GENERATED_HEADER);
    out.push('\n');

    // Imports from client
    emit!(
        out,
        "import {{ type RpcClient, RpcError, type CallOptions }} from \"{client_import_path}\";\n"
    );

    // Imports from types
    let type_names: Vec<&str> = manifest
        .structs
        .iter()
        .map(|s| s.name.as_str())
        .chain(manifest.enums.iter().map(|e| e.name.as_str()))
        .collect();

    if type_names.is_empty() {
        emit!(
            out,
            "import type {{ Procedures }} from \"{types_import_path}\";\n"
        );
    } else {
        let types_csv = type_names.join(", ");
        emit!(
            out,
            "import type {{ Procedures, {types_csv} }} from \"{types_import_path}\";\n"
        );
    }

    // Re-exports
    emit!(out, "export {{ RpcError }};");
    if type_names.is_empty() {
        emit!(
            out,
            "export type {{ RpcClient, CallOptions, Procedures }};\n"
        );
    } else {
        let types_csv = type_names.join(", ");
        emit!(
            out,
            "export type {{ RpcClient, CallOptions, Procedures, {types_csv} }};\n"
        );
    }

    // Type helpers
    if has_queries {
        emit!(out, "type QueryKey = keyof Procedures[\"queries\"];");
        emit!(
            out,
            "type QueryInput<K extends QueryKey> = Procedures[\"queries\"][K][\"input\"];"
        );
        emit!(
            out,
            "type QueryOutput<K extends QueryKey> = Procedures[\"queries\"][K][\"output\"];"
        );
    }
    if has_mutations {
        emit!(out, "type MutationKey = keyof Procedures[\"mutations\"];");
        emit!(
            out,
            "type MutationInput<K extends MutationKey> = Procedures[\"mutations\"][K][\"input\"];"
        );
        emit!(
            out,
            "type MutationOutput<K extends MutationKey> = Procedures[\"mutations\"][K][\"output\"];"
        );
    }
    out.push('\n');

    // Void/non-void key unions and MutationArgs helper
    if has_queries {
        let void_queries: Vec<_> = queries.iter().filter(|p| is_void_input(p)).collect();
        let non_void_queries: Vec<_> = queries.iter().filter(|p| !is_void_input(p)).collect();

        if !void_queries.is_empty() {
            let names: Vec<_> = void_queries
                .iter()
                .map(|p| format!("\"{}\"", p.name))
                .collect();
            emit!(out, "type VoidQueryKey = {};", names.join(" | "));
        }
        if !non_void_queries.is_empty() {
            let names: Vec<_> = non_void_queries
                .iter()
                .map(|p| format!("\"{}\"", p.name))
                .collect();
            emit!(out, "type NonVoidQueryKey = {};", names.join(" | "));
        }
    }
    if has_mutations {
        let void_mutations: Vec<_> = mutations.iter().filter(|p| is_void_input(p)).collect();
        let non_void_mutations: Vec<_> = mutations.iter().filter(|p| !is_void_input(p)).collect();

        if !void_mutations.is_empty() {
            let names: Vec<_> = void_mutations
                .iter()
                .map(|p| format!("\"{}\"", p.name))
                .collect();
            emit!(out, "type VoidMutationKey = {};", names.join(" | "));
        }
        if !non_void_mutations.is_empty() {
            let names: Vec<_> = non_void_mutations
                .iter()
                .map(|p| format!("\"{}\"", p.name))
                .collect();
            emit!(out, "type NonVoidMutationKey = {};", names.join(" | "));
        }

        // MutationArgs helper type
        let all_void = non_void_mutations.is_empty();
        let all_non_void = void_mutations.is_empty();
        if all_void {
            emit!(out, "type MutationArgs<K extends MutationKey> = [];");
        } else if all_non_void {
            emit!(
                out,
                "type MutationArgs<K extends MutationKey> = [input: MutationInput<K>];"
            );
        } else {
            emit!(
                out,
                "type MutationArgs<K extends MutationKey> = K extends VoidMutationKey ? [] : [input: MutationInput<K>];"
            );
        }
    }
    out.push('\n');

    // Interfaces
    if has_queries {
        emit!(out, "{QUERY_OPTIONS_INTERFACE}\n");
        emit!(out, "{QUERY_RESULT_INTERFACE}\n");
    }
    if has_mutations {
        emit!(out, "{MUTATION_OPTIONS_INTERFACE}\n");
        emit!(out, "{MUTATION_RESULT_INTERFACE}\n");
    }

    // createQuery overloads + implementation
    if has_queries {
        emit!(out, "{IS_QUERY_OPTIONS_IMPL}\n");
        generate_query_overloads(&queries, &mut out);
        emit!(out, "{CREATE_QUERY_IMPL}\n");
    }

    // createMutation
    if has_mutations {
        emit!(out, "{CREATE_MUTATION_IMPL}\n");
    }

    out
}

/// Generates TypeScript overload signatures for `createQuery`.
fn generate_query_overloads(queries: &[&Procedure], out: &mut String) {
    let (void_queries, non_void_queries): (Vec<&&Procedure>, Vec<&&Procedure>) =
        queries.iter().partition(|p| is_void_input(p));

    // Void-input overloads (no input parameter)
    for proc in &void_queries {
        let output_ts = proc
            .output
            .as_ref()
            .map(rust_type_to_ts)
            .unwrap_or_else(|| "void".to_string());
        emit!(
            out,
            "export function createQuery<K extends \"{}\">(client: RpcClient, key: K, options?: QueryOptions<K> | (() => QueryOptions<K>)): QueryResult<K>;",
            proc.name,
        );
        let _ = output_ts; // type safety ensured by generic K
    }

    // Non-void-input overloads (requires input getter)
    for proc in &non_void_queries {
        let output_ts = proc
            .output
            .as_ref()
            .map(rust_type_to_ts)
            .unwrap_or_else(|| "void".to_string());
        emit!(
            out,
            "export function createQuery<K extends \"{}\">(client: RpcClient, key: K, input: () => QueryInput<K>, options?: QueryOptions<K> | (() => QueryOptions<K>)): QueryResult<K>;",
            proc.name,
        );
        let _ = output_ts;
    }
}

/// Returns `true` if the procedure takes no input (void).
fn is_void_input(proc: &Procedure) -> bool {
    proc.input.as_ref().is_none_or(|ty| ty.name == "()")
}
