use crate::model::{Manifest, Procedure, ProcedureKind};

use super::typescript::rust_type_to_ts;

const GENERATED_HEADER: &str = "\
// This file is auto-generated by vercel-rpc-cli. Do not edit manually.
// Re-run `rpc generate` or use `rpc watch` to regenerate.
";

const QUERY_OPTIONS_INTERFACE: &str = r#"export interface QueryOptions<K extends QueryKey> {
  /** Whether to execute the query. Reactive when passed as a getter. @default true */
  enabled?: boolean | (() => boolean);

  /** Auto-refetch interval in milliseconds. Set to 0 or omit to disable. */
  refetchInterval?: number;

  /** Initial data shown before the first fetch completes. */
  placeholderData?: QueryOutput<K>;

  /** Per-call options forwarded to client.query(). */
  callOptions?: CallOptions;

  /** Called when the query succeeds. */
  onSuccess?: (data: QueryOutput<K>) => void;

  /** Called when the query fails. */
  onError?: (error: RpcError) => void;

  /** Called when the query settles (success or failure). */
  onSettled?: () => void;
}"#;

const QUERY_RESULT_INTERFACE: &str = r#"export interface QueryResult<K extends QueryKey> {
  /** The latest successfully resolved data, or placeholderData. */
  readonly data: QueryOutput<K> | undefined;

  /** The error from the most recent failed fetch, cleared on success. */
  readonly error: RpcError | undefined;

  /** True while a fetch is in-flight (including the initial fetch). */
  readonly isLoading: boolean;

  /** True after the first successful fetch. Stays true across refetches. */
  readonly isSuccess: boolean;

  /** True when error is set. */
  readonly isError: boolean;

  /** Manually trigger a refetch. */
  refetch: () => Promise<void>;
}"#;

const MUTATION_OPTIONS_INTERFACE: &str = r#"export interface MutationOptions<K extends MutationKey> {
  /** Per-call options forwarded to client.mutate(). */
  callOptions?: CallOptions;

  /** Called when the mutation succeeds. */
  onSuccess?: (data: MutationOutput<K>) => void;

  /** Called when the mutation fails. */
  onError?: (error: RpcError) => void;

  /** Called when the mutation settles (success or failure). */
  onSettled?: () => void;
}"#;

const MUTATION_RESULT_INTERFACE: &str = r#"export interface MutationResult<K extends MutationKey> {
  /** Execute the mutation. Rejects on error. */
  mutate: (...args: MutationArgs<K>) => Promise<void>;

  /** Execute the mutation and return the result. Rejects on error. */
  mutateAsync: (...args: MutationArgs<K>) => Promise<MutationOutput<K>>;

  /** The latest successfully resolved data. */
  readonly data: MutationOutput<K> | undefined;

  /** The error from the most recent failed mutation, cleared on next attempt. */
  readonly error: RpcError | undefined;

  /** True while a mutation is in-flight. */
  readonly isLoading: boolean;

  /** True after the most recent mutation succeeded. */
  readonly isSuccess: boolean;

  /** True when error is set. */
  readonly isError: boolean;

  /** Reset state back to idle (clear data, error, status). */
  reset: () => void;
}"#;

const CREATE_QUERY_IMPL: &str = r#"export function createQuery<K extends QueryKey>(
  client: RpcClient,
  ...args: unknown[]
): QueryResult<K> {
  const key = args[0] as K;

  const inputFn = typeof args[1] === "function"
    ? args[1] as () => QueryInput<K>
    : undefined;
  const options = (typeof args[1] === "object" ? args[1] : args[2]) as
    | QueryOptions<K>
    | undefined;

  let data = $state<QueryOutput<K> | undefined>(options?.placeholderData);
  let error = $state<RpcError | undefined>();
  let isLoading = $state(true);

  async function fetchData() {
    const enabled = typeof options?.enabled === "function"
      ? options.enabled()
      : (options?.enabled ?? true);
    if (!enabled) return;

    isLoading = true;
    error = undefined;
    try {
      const input = inputFn?.();
      const args: unknown[] = [key];
      if (input !== undefined) args.push(input);
      if (options?.callOptions) args.push(options.callOptions);
      data = await (client.query as Function)(...args) as QueryOutput<K>;
      options?.onSuccess?.(data!);
    } catch (e) {
      error = e as RpcError;
      options?.onError?.(error);
    } finally {
      isLoading = false;
      options?.onSettled?.();
    }
  }

  $effect(() => {
    const enabled = typeof options?.enabled === "function"
      ? options.enabled()
      : (options?.enabled ?? true);
    if (inputFn) inputFn();
    if (!enabled) return;

    void fetchData();

    if (options?.refetchInterval) {
      const interval = setInterval(fetchData, options.refetchInterval);
      return () => clearInterval(interval);
    }
  });

  return {
    get data() { return data; },
    get error() { return error; },
    get isLoading() { return isLoading; },
    get isSuccess() { return data !== undefined; },
    get isError() { return error !== undefined; },
    refetch: fetchData,
  };
}"#;

const CREATE_MUTATION_IMPL: &str = r#"export function createMutation<K extends MutationKey>(
  client: RpcClient,
  key: K,
  options?: MutationOptions<K>,
): MutationResult<K> {
  let data = $state<MutationOutput<K> | undefined>();
  let error = $state<RpcError | undefined>();
  let isLoading = $state(false);

  async function execute(...input: unknown[]): Promise<MutationOutput<K>> {
    isLoading = true;
    error = undefined;
    try {
      const args: unknown[] = [key];
      if (input.length > 0) args.push(input[0]);
      if (options?.callOptions) args.push(options.callOptions);
      const result = await (client.mutate as Function)(...args) as MutationOutput<K>;
      data = result;
      options?.onSuccess?.(result);
      return result;
    } catch (e) {
      error = e as RpcError;
      options?.onError?.(error);
      throw e;
    } finally {
      isLoading = false;
      options?.onSettled?.();
    }
  }

  return {
    mutate: async (...args: unknown[]) => { await execute(...args); },
    mutateAsync: (...args: unknown[]) => execute(...args),
    get data() { return data; },
    get error() { return error; },
    get isLoading() { return isLoading; },
    get isSuccess() { return data !== undefined && error === undefined; },
    get isError() { return error !== undefined; },
    reset: () => { data = undefined; error = undefined; isLoading = false; },
  } as MutationResult<K>;
}"#;

/// Generates the complete Svelte 5 reactive wrapper file content from a manifest.
///
/// Returns an empty string when the manifest contains no procedures (the caller
/// should skip writing the file in that case).
pub fn generate_svelte_file(
    manifest: &Manifest,
    client_import_path: &str,
    types_import_path: &str,
    _preserve_docs: bool,
) -> String {
    let queries: Vec<_> = manifest
        .procedures
        .iter()
        .filter(|p| p.kind == ProcedureKind::Query)
        .collect();
    let mutations: Vec<_> = manifest
        .procedures
        .iter()
        .filter(|p| p.kind == ProcedureKind::Mutation)
        .collect();

    if queries.is_empty() && mutations.is_empty() {
        return String::new();
    }

    let has_queries = !queries.is_empty();
    let has_mutations = !mutations.is_empty();

    let mut out = String::with_capacity(4096);

    // Header
    out.push_str(GENERATED_HEADER);
    out.push('\n');

    // Imports from client
    emit!(
        out,
        "import {{ type RpcClient, RpcError, type CallOptions }} from \"{client_import_path}\";\n"
    );

    // Imports from types
    let type_names: Vec<&str> = manifest
        .structs
        .iter()
        .map(|s| s.name.as_str())
        .chain(manifest.enums.iter().map(|e| e.name.as_str()))
        .collect();

    if type_names.is_empty() {
        emit!(
            out,
            "import type {{ Procedures }} from \"{types_import_path}\";\n"
        );
    } else {
        let types_csv = type_names.join(", ");
        emit!(
            out,
            "import type {{ Procedures, {types_csv} }} from \"{types_import_path}\";\n"
        );
    }

    // Re-exports
    emit!(out, "export {{ RpcError }};");
    if type_names.is_empty() {
        emit!(
            out,
            "export type {{ RpcClient, CallOptions, Procedures }};\n"
        );
    } else {
        let types_csv = type_names.join(", ");
        emit!(
            out,
            "export type {{ RpcClient, CallOptions, Procedures, {types_csv} }};\n"
        );
    }

    // Type helpers
    if has_queries {
        emit!(out, "type QueryKey = keyof Procedures[\"queries\"];");
        emit!(
            out,
            "type QueryInput<K extends QueryKey> = Procedures[\"queries\"][K][\"input\"];"
        );
        emit!(
            out,
            "type QueryOutput<K extends QueryKey> = Procedures[\"queries\"][K][\"output\"];"
        );
    }
    if has_mutations {
        emit!(out, "type MutationKey = keyof Procedures[\"mutations\"];");
        emit!(
            out,
            "type MutationInput<K extends MutationKey> = Procedures[\"mutations\"][K][\"input\"];"
        );
        emit!(
            out,
            "type MutationOutput<K extends MutationKey> = Procedures[\"mutations\"][K][\"output\"];"
        );
    }
    out.push('\n');

    // Void/non-void key unions and MutationArgs helper
    if has_queries {
        let void_queries: Vec<_> = queries.iter().filter(|p| is_void_input(p)).collect();
        let non_void_queries: Vec<_> = queries.iter().filter(|p| !is_void_input(p)).collect();

        if !void_queries.is_empty() {
            let names: Vec<_> = void_queries
                .iter()
                .map(|p| format!("\"{}\"", p.name))
                .collect();
            emit!(out, "type VoidQueryKey = {};", names.join(" | "));
        }
        if !non_void_queries.is_empty() {
            let names: Vec<_> = non_void_queries
                .iter()
                .map(|p| format!("\"{}\"", p.name))
                .collect();
            emit!(out, "type NonVoidQueryKey = {};", names.join(" | "));
        }
    }
    if has_mutations {
        let void_mutations: Vec<_> = mutations.iter().filter(|p| is_void_input(p)).collect();
        let non_void_mutations: Vec<_> = mutations.iter().filter(|p| !is_void_input(p)).collect();

        if !void_mutations.is_empty() {
            let names: Vec<_> = void_mutations
                .iter()
                .map(|p| format!("\"{}\"", p.name))
                .collect();
            emit!(out, "type VoidMutationKey = {};", names.join(" | "));
        }
        if !non_void_mutations.is_empty() {
            let names: Vec<_> = non_void_mutations
                .iter()
                .map(|p| format!("\"{}\"", p.name))
                .collect();
            emit!(out, "type NonVoidMutationKey = {};", names.join(" | "));
        }

        // MutationArgs helper type
        let all_void = non_void_mutations.is_empty();
        let all_non_void = void_mutations.is_empty();
        if all_void {
            emit!(out, "type MutationArgs<K extends MutationKey> = [];");
        } else if all_non_void {
            emit!(
                out,
                "type MutationArgs<K extends MutationKey> = [input: MutationInput<K>];"
            );
        } else {
            emit!(
                out,
                "type MutationArgs<K extends MutationKey> = K extends VoidMutationKey ? [] : [input: MutationInput<K>];"
            );
        }
    }
    out.push('\n');

    // Interfaces
    if has_queries {
        emit!(out, "{QUERY_OPTIONS_INTERFACE}\n");
        emit!(out, "{QUERY_RESULT_INTERFACE}\n");
    }
    if has_mutations {
        emit!(out, "{MUTATION_OPTIONS_INTERFACE}\n");
        emit!(out, "{MUTATION_RESULT_INTERFACE}\n");
    }

    // createQuery overloads + implementation
    if has_queries {
        generate_query_overloads(&queries, &mut out);
        emit!(out, "{CREATE_QUERY_IMPL}\n");
    }

    // createMutation
    if has_mutations {
        emit!(out, "{CREATE_MUTATION_IMPL}\n");
    }

    out
}

/// Generates TypeScript overload signatures for `createQuery`.
fn generate_query_overloads(queries: &[&Procedure], out: &mut String) {
    let (void_queries, non_void_queries): (Vec<&&Procedure>, Vec<&&Procedure>) =
        queries.iter().partition(|p| is_void_input(p));

    // Void-input overloads (no input parameter)
    for proc in &void_queries {
        let output_ts = proc
            .output
            .as_ref()
            .map(rust_type_to_ts)
            .unwrap_or_else(|| "void".to_string());
        emit!(
            out,
            "export function createQuery<K extends \"{}\">(client: RpcClient, key: K, options?: QueryOptions<K>): QueryResult<K>;",
            proc.name,
        );
        let _ = output_ts; // type safety ensured by generic K
    }

    // Non-void-input overloads (requires input getter)
    for proc in &non_void_queries {
        let output_ts = proc
            .output
            .as_ref()
            .map(rust_type_to_ts)
            .unwrap_or_else(|| "void".to_string());
        emit!(
            out,
            "export function createQuery<K extends \"{}\">(client: RpcClient, key: K, input: () => QueryInput<K>, options?: QueryOptions<K>): QueryResult<K>;",
            proc.name,
        );
        let _ = output_ts;
    }
}

/// Returns `true` if the procedure takes no input (void).
fn is_void_input(proc: &Procedure) -> bool {
    proc.input.as_ref().is_none_or(|ty| ty.name == "()")
}
