title: "[Idea] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Ideas & Feature Requests

        Share your ideas for improving **vercel-rpc / svelte-rust**!

        We'd love to hear about new features, improvements to existing functionality, or integrations you'd like to see.
  - type: textarea
    id: idea
    attributes:
      label: Idea
      description: Describe your idea or feature request.
      placeholder: What would you like to see added or changed?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this useful? What problem does it solve?
      placeholder: Explain the use case or pain point...
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: How do you envision this working? (optional)
      placeholder: API design, code examples, or rough sketch...
    validations:
      required: false
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the project does this relate to?
      options:
        - "Rust macros (#[rpc_query] / #[rpc_mutation])"
        - "CLI (scan / generate / watch)"
        - "TypeScript codegen (types / client)"
        - "SvelteKit integration"
        - "Vercel deployment"
        - "Documentation"
        - "Other"
    validations:
      required: true
