name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request

        Suggest a new feature or improvement for **vercel-rpc / svelte-rust**!

        For open-ended ideas and brainstorming, consider using [Discussions](https://github.com/misha-mad/svelte-rust/discussions/categories/ideas) instead.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature.
      placeholder: What would you like to see added or changed?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this useful? What problem does it solve?
      placeholder: Explain the use case or pain point...
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: How do you envision this working?
      placeholder: API design, code examples, or rough sketch...
    validations:
      required: false
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the project does this relate to?
      options:
        - "Rust macros (#[rpc_query] / #[rpc_mutation])"
        - "CLI (scan / generate / watch)"
        - "TypeScript codegen (types / client)"
        - "SvelteKit integration"
        - "Vercel deployment"
        - "Documentation"
        - "Other"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or features you've considered.
      placeholder: Describe alternatives...
    validations:
      required: false
