//! End-to-end typesafe RPC between Rust lambdas on Vercel and any TypeScript frontend.
//!
//! This crate is a facade that re-exports the [`vercel-rpc-macro`] proc macros together
//! with all runtime dependencies they need. Users only have to add two dependencies:
//!
//! ```toml
//! [dependencies]
//! vercel-rpc = "0.1"
//! serde = { version = "1", features = ["derive"] }
//! ```
//!
//! # Quick Start
//!
//! ```rust,ignore
//! use vercel_rpc::rpc_query;
//!
//! #[rpc_query]
//! async fn hello(name: String) -> String {
//!     format!("Hello, {}!", name)
//! }
//! ```

pub use vercel_rpc_macro::{rpc_mutation, rpc_query};

pub use serde::{Deserialize, Serialize};

/// Hidden re-exports consumed by code generated by the proc macros.
/// Not part of the public API — do not depend on these directly.
#[doc(hidden)]
pub mod __private {
    pub use http_body_util;
    pub use serde_json;
    pub use tokio;
    pub use url;
    pub use vercel_runtime;
}
