// This file is auto-generated by vercel-rpc-cli. Do not edit manually.
// Re-run `rpc generate` or use `rpc watch` to regenerate.

/** Snapshot of service health and version info. */
export interface ServiceStatus {
  serviceName: string;
  status: HealthStatus;
  uptimeSecs: number;
  apiVersion: string;
  isHealthy: boolean;
}

/** Overall health of the service. */
export type HealthStatus = "Healthy" | "Degraded" | "Down";

export type Procedures = {
  queries: {
    /** Returns current service health, uptime, and version. */
    status: { input: void; output: ServiceStatus };
  };
  mutations: {
  };
};
