// This file is auto-generated by metaxy-cli. Do not edit manually.
// Re-run `metaxy generate` or use `metaxy watch` to regenerate.

/** Demonstrates precision loss when large `u64` values are mapped to JS `number`. */
export interface BigIntDemoResponse {
  values: BigIntDemoValue[];
}

/** A single row showing a u64 value with its exact string representation. */
export interface BigIntDemoValue {
  label: string;
  exact: string;
  as_number: number;
}

/** Server timestamp with private (browser-only) cache. */
export interface CachedTimePrivateResponse {
  timestamp: number;
  generated_at: string;
}

/** Cached server timestamp — public CDN cache for 30 seconds. */
export interface CachedTimeResponse {
  timestamp: number;
  generated_at: string;
}

/** Server timestamp with stale-while-revalidate. */
export interface CachedTimeStaleResponse {
  timestamp: number;
  generated_at: string;
}

export interface CookieDemoResponse {
  authenticated: boolean;
  message: string;
  cookie_value: string | null;
}

export interface DedupDemoResponse {
  request_number: number;
  timestamp: string;
}

/** Input for the echo mutation. */
export interface EchoInput {
  message: string;
  uppercase: boolean;
}

/** Output returned by the echo mutation. */
export interface EchoOutput {
  original: string;
  transformed: string;
  length: number;
}

export interface IdempotentDemoInput {
  value: number;
}

export interface IdempotentDemoResponse {
  previous: number;
  current: number;
  total_calls: number;
}

export interface InitDemoResponse {
  cold_start_at: number;
  init_duration_ms: number;
  request_count: number;
  now: number;
}

/** Input for a math calculation. */
export interface MathInput {
  a: number;
  b: number;
  op: Operation;
}

/** Result of a math calculation with a formatted expression. */
export interface MathResult {
  result: number;
  expression: string;
}

/** Server timestamp with a human-readable message. */
export interface TimeResponse {
  timestamp: number;
  message: string;
}

export interface TimeoutDemoInput {
  sleep_ms: number;
}

export interface TimeoutDemoResponse {
  requested_ms: number;
  actual_ms: number;
  timeout_ms: number;
}

/** Showcases every Rust → TypeScript type mapping in a single struct. */
export interface TypeShowcase {
  string_val: string;
  integer: number;
  float: number;
  flag: boolean;
  vec_items: string[];
  hash_set: string[];
  btree_set: number[];
  optional_present: string | null;
  optional_absent: string | null;
  hash_map: Record<string, number>;
  btree_map: Record<string, number>;
  boxed: string;
  cow: string;
  tuple: [string, number, boolean];
  fixed_array: number[];
}

/** Arithmetic operation to perform. */
export type Operation = "Add" | "Subtract" | "Multiply" | "Divide";

export type Procedures = {
  queries: {
    /** Return a set of u64 values at precision boundaries. */
    bigint_demo: { input: void; output: BigIntDemoResponse };
    /** Returns server time, cached on CDN for 30 seconds. */
    cached_time: { input: void; output: CachedTimeResponse };
    /** Returns server time, cached in browser only for 1 minute (no CDN). */
    cached_time_private: { input: void; output: CachedTimePrivateResponse };
    /** Returns server time, cached 10s + stale for 30s while revalidating. */
    cached_time_stale: { input: void; output: CachedTimeStaleResponse };
    /**
     * Checks for a `session` cookie in the request headers.
     * Returns OK if present, error details if missing.
     */
    cookie_demo: { input: void; output: CookieDemoResponse };
    /**
     * Slow endpoint (500ms) with a request counter.
     * Used to demonstrate request deduplication.
     */
    dedup_demo: { input: void; output: DedupDemoResponse };
    /**
     * Greet a user by name.
     * Returns a personalized greeting string.
     */
    hello: { input: string; output: string };
    init_demo: { input: void; output: InitDemoResponse };
    /** Perform a math operation. Returns an error on division by zero. */
    math: { input: MathInput; output: MathResult };
    /**
     * Access a protected secret.
     * Requires a valid Bearer token in the Authorization header.
     */
    secret: { input: void; output: string };
    /** Returns the current server time as a Unix timestamp. */
    time: { input: void; output: TimeResponse };
    timeout_demo: { input: TimeoutDemoInput; output: TimeoutDemoResponse };
    /** Return a showcase of every supported type mapping. */
    types: { input: void; output: TypeShowcase };
  };
  mutations: {
    /** Echo a message back, optionally transforming it to uppercase. */
    echo: { input: EchoInput; output: EchoOutput };
    /**
     * Idempotent upsert: sets the stored value. Repeated calls with the same
     * input produce the same result, making it safe to retry on failure.
     */
    idempotent_demo: { input: IdempotentDemoInput; output: IdempotentDemoResponse };
  };
};
