// This file is auto-generated by metaxy-cli. Do not edit manually.
// Re-run `metaxy generate` or use `metaxy watch` to regenerate.

/**
 * Demonstrates `number` vs `bigint` precision for large integers.
 * 
 * Each row carries the same value as both `u64` (`number`) and
 * `u128` (`bigint`). Compare them to see where `number` loses
 * precision and `bigint` stays exact.
 */
export interface BigIntDemoResponse {
  values: BigIntDemoValue[];
}

/** A single row comparing `number` (u64) vs `bigint` (u128) for the same value. */
export interface BigIntDemoValue {
  label: string;
  exact: string;
  as_number: number;
  as_bigint: bigint;
}

/** Server timestamp with private (browser-only) cache. */
export interface CachedTimePrivateResponse {
  timestamp: number;
  generated_at: string;
}

/** Cached server timestamp — public CDN cache for 30 seconds. */
export interface CachedTimeResponse {
  timestamp: number;
  generated_at: string;
}

/** Server timestamp with stale-while-revalidate. */
export interface CachedTimeStaleResponse {
  timestamp: number;
  generated_at: string;
}

/** Input for the echo mutation. */
export interface EchoInput {
  message: string;
  uppercase: boolean;
}

/** Output returned by the echo mutation. */
export interface EchoOutput {
  original: string;
  transformed: string;
  length: number;
}

export interface IdempotentDemoInput {
  value: number;
}

export interface IdempotentDemoResponse {
  previous: number;
  current: number;
  total_calls: number;
}

export interface InitDemoResponse {
  cold_start_at: number;
  init_duration_ms: number;
  request_count: number;
  now: number;
}

/** Input for a math calculation. */
export interface MathInput {
  a: number;
  b: number;
  op: Operation;
}

/** Result of a math calculation with a formatted expression. */
export interface MathResult {
  result: number;
  expression: string;
}

/** Snapshot of service health and version info. */
export interface ServiceStatus {
  name: string;
  status: HealthStatus;
  uptime_secs: number;
  version: string;
}

/** Descriptive statistics for a list of numbers. */
export interface Stats {
  count: number;
  sum: number;
  mean: number;
  min: number;
  max: number;
  frequencies: Record<string, number>;
}

/** Server timestamp with a human-readable message. */
export interface TimeResponse {
  timestamp: number;
  message: string;
}

export interface TimeoutDemoInput {
  sleep_ms: number;
}

export interface TimeoutDemoResponse {
  requested_ms: number;
  actual_ms: number;
  timeout_ms: number;
}

/** Showcases every Rust → TypeScript type mapping in a single struct. */
export interface TypeShowcase {
  string_val: string;
  integer: number;
  float: number;
  flag: boolean;
  vec_items: string[];
  hash_set: string[];
  btree_set: number[];
  optional_present: string | null;
  optional_absent: string | null;
  hash_map: Record<string, number>;
  btree_map: Record<string, number>;
  boxed: string;
  cow: string;
  tuple: [string, number, boolean];
  fixed_array: number[];
}

/**
 * A user profile with camelCase fields in JSON.
 * 
 * Demonstrates `rename_all`, per-field `rename`, `skip`, and `default`.
 */
export interface UserProfile {
  userId: number;
  displayName: string;
  emailAddress: string;
  role: UserRole;
  lastEvent: EventKind;
  profile_url: string;
  avatarUrl?: string | null;
}

/**
 * Account event kind with kebab-case serialization.
 * Produces: `"sign-in"`, `"sign-out"`, `"password-reset"`.
 */
export type EventKind = "sign-in" | "sign-out" | "password-reset";

/** Overall health of the service. */
export type HealthStatus = "Healthy" | "Degraded" | "Down";

/** Arithmetic operation to perform. */
export type Operation = "Add" | "Subtract" | "Multiply" | "Divide";

/**
 * User role with snake_case serialization.
 * Produces: `"admin"`, `"power_user"`, `"guest"`.
 */
export type UserRole = "admin" | "power_user" | "anonymous";

export type Procedures = {
  queries: {
    /** Return a set of u64 values at precision boundaries. */
    bigint_demo: { input: void; output: BigIntDemoResponse };
    /** Returns server time, cached on CDN for 30 seconds. */
    cached_time: { input: void; output: CachedTimeResponse };
    /** Returns server time, cached in browser only for 1 minute (no CDN). */
    cached_time_private: { input: void; output: CachedTimePrivateResponse };
    /** Returns server time, cached 10s + stale for 30s while revalidating. */
    cached_time_stale: { input: void; output: CachedTimeStaleResponse };
    /**
     * Greet a user by name.
     * Returns a personalized greeting string.
     */
    hello: { input: string; output: string };
    init_demo: { input: void; output: InitDemoResponse };
    /** Perform a math operation. Returns an error on division by zero. */
    math: { input: MathInput; output: MathResult };
    /**
     * Look up a user profile by ID.
     * 
     * Showcases serde attributes: `rename_all`, `rename`, `skip`, `default`
     * on structs and enums to demonstrate TypeScript codegen fidelity.
     */
    profile: { input: number; output: UserProfile };
    /**
     * Access a protected secret.
     * Requires a valid Bearer token in the Authorization header.
     */
    secret: { input: void; output: string };
    /** Compute descriptive statistics for a list of numbers. */
    stats: { input: number[]; output: Stats };
    /** Returns current service health, uptime, and version. */
    status: { input: void; output: ServiceStatus };
    /** Returns the current server time as a Unix timestamp. */
    time: { input: void; output: TimeResponse };
    timeout_demo: { input: TimeoutDemoInput; output: TimeoutDemoResponse };
    /** Return a showcase of every supported type mapping. */
    types: { input: void; output: TypeShowcase };
  };
  mutations: {
    /** Echo a message back, optionally transforming it to uppercase. */
    echo: { input: EchoInput; output: EchoOutput };
    /**
     * Idempotent upsert: sets the stored value. Repeated calls with the same
     * input produce the same result, making it safe to retry on failure.
     */
    idempotent_demo: { input: IdempotentDemoInput; output: IdempotentDemoResponse };
  };
};
